name: Run MATLAB command
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  main:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        release: [R2020b, R2021a]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.release }}
          cache: true
      - name: Say Hello World!
        uses: matlab-actions/run-command@v1
        with:
          command: |
            disp("Hello World!")
